handle and launch on multiple screens
CypherpunkArmory/UserLAnd pull request #976
Opened 2019-08-01 08:53 UTC by jlainema

**Note**
Pull requests should follow the git flow described in the [wiki](https://github.com/CypherpunkArmory/UserLAnd/wiki/Git-flow).
To get git history clean and aid in more useful release notes, it is essential to use the `Squash and merge` option when
merging into 'master', and the `Create merge commit` option when merging into 'releases'.

## What changes does this PR introduce?

Fixes an issue with view changes starting multiple new sessions.

Launches and migrates sessions to external screens, when they are plugged in (and back to device screen when they are plugged out).

## Any background context you want to provide?

I am venturing into the maddeningly recursive depths of actually doing development on Android (eventually for Android). Having an external screen that works seamlessly is nearly a requirement for this.

## Where should the reviewer start?

Simple change, just look through it all.

## Has this been manually tested? How?

Plugging & unplugging a USB monitor to an Android-Q Oneplus 7 developer preview 3. Connecting & disconnecting a Bluetooth keyboard on the same device.

## What value does this provide to our end users?

Fullscreen desktop-like experience when external monitors are plugged in while running UserLAnd.

## What GIF best describes this PR or how it makes you feel?
![](https://thumbs.gfycat.com/UntidyDistantFanworms-small.gif)

2019-08-10 06:37 UTC, ghost reviewed
multiple screens?

2019-08-10 06:41 UTC, ghost requested changes
multiple screens?

2019-08-11 06:08 UTC, ghost requested changes
multiple screens

2019-08-11 06:11 UTC, qqqwwweee123-arch commented
handle and launch on multiple screen?

2019-08-14 19:00 UTC, MatthewTighe commented
Any suggestions on how this could be tested without access to more physical screens?

2019-08-14 19:12 UTC, jlainema commented
It should work with wireless displays as well. I think you should be able to cast to pretty much any laptop over wifi if you not have other miracast devices and no thunderbolt capable android device.

In android Q, there would also be a developer option to create a virtual display to a window directly on the device.

2019-08-15 08:05 UTC, maysusan commented
Thank

2019-08-15 08:06 UTC, maysusan approved these changes

2019-08-15 08:06 UTC, jlainema commented
Changed the "desktop mode" commit description, and added FLAG_KEEP_SCREEN_ON for the external display when both hardware keyboard and external display are available.

I would have expected this to keep the external display awake, while allowing the phone screen to sleep when working on the activity on the external display; but at least my device keeps both the phone display and the external display awake (this is probably an issue in Android, need to investigate further eventually).

2019-11-04 18:59 UTC, corbinlc commented
I am sorry we never got back to this.  We had a large funding change about the time we were discussion this with you.  I will look at this, this week or next.  It looks like pretty good work.

2020-05-08 04:50 UTC, gyggyg234 commented
How

2020-05-08 04:55 UTC, gyggyg234 approved these changes

2020-10-27 18:29 UTC, jlaufersweiler commented
I'd be willing to test this with Samsung DeX + the phone screen mirrored to a second monitor via DisplayLink adapter. Would that be a matter of cloning the branch repo to local storage and then pointing F-Droid at it, or is there a more involved build process?

2021-12-17 03:27 UTC, Aidenmichael approved these changes

2026-08-19 20:51 UTC, closed without merging